AWSTemplateFormatVersion: '2010-09-09'
Description: 'NetworkScanScada - Phase 1: Secrets Manager Configuration'

Parameters:
  EnvironmentName:
    Description: Environment name
    Type: String
    Default: production

Resources:
  # ==================== Application Secrets ====================
  ApplicationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub networkscan/${EnvironmentName}/application
      Description: Application configuration secrets
      SecretString: !Sub |
        {
          "APP_KEY": "{{resolve:secretsmanager:networkscan/${EnvironmentName}/app-key:SecretString:key}}",
          "APP_ENV": "${EnvironmentName}",
          "APP_DEBUG": "false",
          "SESSION_LIFETIME": "120",
          "ENCRYPTION_KEY": "{{resolve:secretsmanager:networkscan/${EnvironmentName}/encryption-key:SecretString:key}}"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-app-secrets
        - Key: Environment
          Value: !Ref EnvironmentName

  # ==================== App Key Secret ====================
  AppKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub networkscan/${EnvironmentName}/app-key
      Description: Application encryption key
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: key
        PasswordLength: 64
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-app-key

  # ==================== Encryption Key Secret ====================
  EncryptionKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub networkscan/${EnvironmentName}/encryption-key
      Description: Data encryption key
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: key
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-encryption-key

  # ==================== SMTP Credentials ====================
  SMTPSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub networkscan/${EnvironmentName}/smtp
      Description: SMTP credentials for email notifications
      SecretString: |
        {
          "host": "email-smtp.us-east-1.amazonaws.com",
          "port": "587",
          "username": "PLACEHOLDER",
          "password": "PLACEHOLDER",
          "encryption": "tls",
          "from_address": "noreply@example.com",
          "from_name": "NetworkScan SCADA"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-smtp-secrets

  # ==================== Third Party API Keys ====================
  ThirdPartyAPISecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub networkscan/${EnvironmentName}/third-party-apis
      Description: Third party API credentials
      SecretString: |
        {
          "nvd_api_key": "PLACEHOLDER",
          "shodan_api_key": "PLACEHOLDER",
          "virustotal_api_key": "PLACEHOLDER",
          "slack_webhook_url": "PLACEHOLDER",
          "pagerduty_api_key": "PLACEHOLDER"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-third-party-api-secrets

  # ==================== Database Connection Secret (Reference) ====================
  # Note: The actual DB credentials are managed by Aurora's ManageMasterUserPassword
  # This secret stores the connection configuration
  DatabaseConnectionSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub networkscan/${EnvironmentName}/database-config
      Description: Database connection configuration
      SecretString: !Sub |
        {
          "engine": "mysql",
          "host": "{{resolve:ssm:/${EnvironmentName}/aurora/endpoint}}",
          "port": "3306",
          "database": "network_security_scanner",
          "charset": "utf8mb4",
          "collation": "utf8mb4_unicode_ci"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-db-config

  # ==================== Secrets Access Policy ====================
  SecretsAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${EnvironmentName}-networkscan-secrets-access
      Description: Policy for accessing NetworkScan secrets
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ReadSecrets
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource:
              - !Ref ApplicationSecret
              - !Ref AppKeySecret
              - !Ref EncryptionKeySecret
              - !Ref SMTPSecret
              - !Ref ThirdPartyAPISecret
              - !Ref DatabaseConnectionSecret
              - !ImportValue
                Fn::Sub: ${EnvironmentName}-DBMasterSecretArn
              - !ImportValue
                Fn::Sub: ${EnvironmentName}-RedisAuthSecretArn
          - Sid: DecryptSecrets
            Effect: Allow
            Action:
              - kms:Decrypt
            Resource: '*'
            Condition:
              StringEquals:
                kms:ViaService: !Sub secretsmanager.${AWS::Region}.amazonaws.com

  # ==================== Secrets Rotation Schedule ====================
  AppKeyRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: AppKeySecret
    Properties:
      SecretId: !Ref AppKeySecret
      RotationRules:
        AutomaticallyAfterDays: 90

  # ==================== SSM Parameters for Non-Sensitive Config ====================
  AuroraEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${EnvironmentName}/aurora/endpoint
      Type: String
      Value: !ImportValue
        Fn::Sub: ${EnvironmentName}-AuroraClusterEndpoint
      Description: Aurora cluster endpoint
      Tags:
        Environment: !Ref EnvironmentName

  AuroraReadEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${EnvironmentName}/aurora/read-endpoint
      Type: String
      Value: !ImportValue
        Fn::Sub: ${EnvironmentName}-AuroraReadEndpoint
      Description: Aurora read endpoint
      Tags:
        Environment: !Ref EnvironmentName

  RedisEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${EnvironmentName}/redis/endpoint
      Type: String
      Value: !ImportValue
        Fn::Sub: ${EnvironmentName}-RedisEndpoint
      Description: Redis primary endpoint
      Tags:
        Environment: !Ref EnvironmentName

  S3BucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${EnvironmentName}/s3/reports-bucket
      Type: String
      Value: !Sub ${EnvironmentName}-networkscan-reports
      Description: S3 bucket for reports
      Tags:
        Environment: !Ref EnvironmentName

Outputs:
  ApplicationSecretArn:
    Description: Application secret ARN
    Value: !Ref ApplicationSecret
    Export:
      Name: !Sub ${EnvironmentName}-ApplicationSecretArn

  SMTPSecretArn:
    Description: SMTP secret ARN
    Value: !Ref SMTPSecret
    Export:
      Name: !Sub ${EnvironmentName}-SMTPSecretArn

  SecretsAccessPolicyArn:
    Description: Secrets access policy ARN
    Value: !Ref SecretsAccessPolicy
    Export:
      Name: !Sub ${EnvironmentName}-SecretsAccessPolicyArn
