AWSTemplateFormatVersion: '2010-09-09'
Description: 'NetworkScanScada - Phase 2: EC2, Auto Scaling, and Application Load Balancer'

Parameters:
  EnvironmentName:
    Description: Environment name
    Type: String
    Default: production

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: m6i.xlarge
    AllowedValues:
      - t3.medium
      - t3.large
      - m6i.large
      - m6i.xlarge
      - m6i.2xlarge
      - c6i.xlarge
      - c6i.2xlarge

  KeyPairName:
    Description: EC2 Key Pair name
    Type: AWS::EC2::KeyPair::KeyName
    Default: networkscan-key

  MinSize:
    Description: Minimum number of instances
    Type: Number
    Default: 2

  MaxSize:
    Description: Maximum number of instances
    Type: Number
    Default: 10

  DesiredCapacity:
    Description: Desired number of instances
    Type: Number
    Default: 2

  CertificateArn:
    Description: ACM Certificate ARN for HTTPS
    Type: String
    Default: ''

  HealthCheckPath:
    Description: Health check path
    Type: String
    Default: /api.php?action=health

Conditions:
  HasCertificate: !Not [!Equals [!Ref CertificateArn, '']]

Resources:
  # ==================== IAM Role for EC2 ====================
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-ec2-instance-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - !ImportValue
          Fn::Sub: ${EnvironmentName}-SecretsAccessPolicyArn
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${EnvironmentName}-networkscan-*
                  - !Sub arn:aws:s3:::${EnvironmentName}-networkscan-*/*
        - PolicyName: SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${EnvironmentName}-networkscan-*
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${EnvironmentName}/*

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${EnvironmentName}-ec2-instance-profile
      Roles:
        - !Ref EC2InstanceRole

  # ==================== Launch Template ====================
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${EnvironmentName}-networkscan-lt
      LaunchTemplateData:
        ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyPairName
        IamInstanceProfile:
          Arn: !GetAtt EC2InstanceProfile.Arn
        SecurityGroupIds:
          - !ImportValue
            Fn::Sub: ${EnvironmentName}-ApplicationSecurityGroupId
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 50
              VolumeType: gp3
              Iops: 3000
              Throughput: 125
              Encrypted: true
              DeleteOnTermination: true
        MetadataOptions:
          HttpTokens: required
          HttpPutResponseHopLimit: 1
          HttpEndpoint: enabled
        Monitoring:
          Enabled: true
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub ${EnvironmentName}-networkscan-app
              - Key: Environment
                Value: !Ref EnvironmentName
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: !Sub ${EnvironmentName}-networkscan-volume
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

            # Update system
            dnf update -y

            # Install required packages
            dnf install -y nginx php8.2-fpm php8.2-mysqlnd php8.2-mbstring php8.2-xml php8.2-json php8.2-opcache php8.2-redis amazon-cloudwatch-agent

            # Configure PHP-FPM
            cat > /etc/php-fpm.d/www.conf << 'PHPFPM'
            [www]
            user = nginx
            group = nginx
            listen = /run/php-fpm/www.sock
            listen.owner = nginx
            listen.group = nginx
            pm = dynamic
            pm.max_children = 50
            pm.start_servers = 5
            pm.min_spare_servers = 5
            pm.max_spare_servers = 35
            pm.max_requests = 500
            php_admin_value[error_log] = /var/log/php-fpm/error.log
            php_admin_flag[log_errors] = on
            PHPFPM

            # Configure PHP for production
            cat > /etc/php.d/99-production.ini << 'PHPINI'
            expose_php = Off
            display_errors = Off
            log_errors = On
            error_log = /var/log/php/error.log
            memory_limit = 256M
            max_execution_time = 300
            upload_max_filesize = 50M
            post_max_size = 50M
            session.save_handler = redis
            session.save_path = "tcp://${EnvironmentName}-RedisEndpoint:6379?auth={{resolve:secretsmanager:networkscan/redis-auth:SecretString:password}}"
            opcache.enable = 1
            opcache.memory_consumption = 128
            opcache.interned_strings_buffer = 8
            opcache.max_accelerated_files = 10000
            opcache.validate_timestamps = 0
            PHPINI

            # Configure Nginx
            cat > /etc/nginx/conf.d/networkscan.conf << 'NGINX'
            server {
                listen 80;
                server_name _;
                root /var/www/networkscan;
                index index.php index.html;

                # Security headers
                add_header X-Frame-Options "SAMEORIGIN" always;
                add_header X-Content-Type-Options "nosniff" always;
                add_header X-XSS-Protection "1; mode=block" always;
                add_header Referrer-Policy "strict-origin-when-cross-origin" always;

                # Health check endpoint
                location /health {
                    access_log off;
                    return 200 "OK";
                    add_header Content-Type text/plain;
                }

                location / {
                    try_files $uri $uri/ /index.php?$query_string;
                }

                location ~ \.php$ {
                    fastcgi_pass unix:/run/php-fpm/www.sock;
                    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                    include fastcgi_params;
                    fastcgi_read_timeout 300;
                }

                location ~ /\. {
                    deny all;
                }

                location ~* \.(env|git|htaccess)$ {
                    deny all;
                }
            }
            NGINX

            # Create directories
            mkdir -p /var/www/networkscan
            mkdir -p /var/log/php
            mkdir -p /var/log/php-fpm
            chown -R nginx:nginx /var/www/networkscan
            chown -R nginx:nginx /var/log/php

            # Install CloudWatch agent config
            cat > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json << 'CWAGENT'
            {
              "agent": {
                "metrics_collection_interval": 60,
                "run_as_user": "root"
              },
              "logs": {
                "logs_collected": {
                  "files": {
                    "collect_list": [
                      {
                        "file_path": "/var/log/nginx/access.log",
                        "log_group_name": "/networkscan/${EnvironmentName}/nginx-access",
                        "log_stream_name": "{instance_id}"
                      },
                      {
                        "file_path": "/var/log/nginx/error.log",
                        "log_group_name": "/networkscan/${EnvironmentName}/nginx-error",
                        "log_stream_name": "{instance_id}"
                      },
                      {
                        "file_path": "/var/log/php/error.log",
                        "log_group_name": "/networkscan/${EnvironmentName}/php-error",
                        "log_stream_name": "{instance_id}"
                      },
                      {
                        "file_path": "/var/log/php-fpm/error.log",
                        "log_group_name": "/networkscan/${EnvironmentName}/php-fpm-error",
                        "log_stream_name": "{instance_id}"
                      }
                    ]
                  }
                }
              },
              "metrics": {
                "namespace": "NetworkScan/${EnvironmentName}",
                "metrics_collected": {
                  "cpu": {
                    "measurement": ["cpu_usage_idle", "cpu_usage_user", "cpu_usage_system"],
                    "metrics_collection_interval": 60
                  },
                  "mem": {
                    "measurement": ["mem_used_percent"],
                    "metrics_collection_interval": 60
                  },
                  "disk": {
                    "measurement": ["disk_used_percent"],
                    "metrics_collection_interval": 60,
                    "resources": ["/"]
                  }
                }
              }
            }
            CWAGENT

            # Start services
            systemctl enable nginx php-fpm amazon-cloudwatch-agent
            systemctl start nginx php-fpm amazon-cloudwatch-agent

            # Signal success
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}

  # ==================== Application Load Balancer ====================
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-networkscan-alb
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      SecurityGroups:
        - !ImportValue
          Fn::Sub: ${EnvironmentName}-ALBSecurityGroupId
      Subnets:
        - !ImportValue
          Fn::Sub: ${EnvironmentName}-PublicSubnet1Id
        - !ImportValue
          Fn::Sub: ${EnvironmentName}-PublicSubnet2Id
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: 'true'
        - Key: routing.http2.enabled
          Value: 'true'
        - Key: access_logs.s3.enabled
          Value: 'true'
        - Key: access_logs.s3.bucket
          Value: !Sub ${EnvironmentName}-networkscan-logs
        - Key: access_logs.s3.prefix
          Value: alb
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-networkscan-alb

  # ==================== Target Group ====================
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-networkscan-tg
      Port: 80
      Protocol: HTTP
      VpcId: !ImportValue
        Fn::Sub: ${EnvironmentName}-VpcId
      TargetType: instance
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: '200'
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: 'true'
        - Key: stickiness.type
          Value: lb_cookie
        - Key: stickiness.lb_cookie.duration_seconds
          Value: '3600'
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-networkscan-tg

  # ==================== Listeners ====================
  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: HasCertificate
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # ==================== Auto Scaling Group ====================
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${EnvironmentName}-networkscan-asg
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      VPCZoneIdentifier:
        - !ImportValue
          Fn::Sub: ${EnvironmentName}-PrivateSubnet1Id
        - !ImportValue
          Fn::Sub: ${EnvironmentName}-PrivateSubnet2Id
      TargetGroupARNs:
        - !Ref TargetGroup
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      TerminationPolicies:
        - OldestInstance
      MetricsCollection:
        - Granularity: 1Minute
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-networkscan-app
          PropagateAtLaunch: true
        - Key: Environment
          Value: !Ref EnvironmentName
          PropagateAtLaunch: true
    CreationPolicy:
      ResourceSignal:
        Count: !Ref DesiredCapacity
        Timeout: PT15M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 1
        PauseTime: PT10M
        WaitOnResourceSignals: true

  # ==================== Scaling Policies ====================
  ScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 70
        DisableScaleIn: false

  ScaleUpMemoryPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        CustomizedMetricSpecification:
          MetricName: mem_used_percent
          Namespace: !Sub NetworkScan/${EnvironmentName}
          Statistic: Average
        TargetValue: 80
        DisableScaleIn: false

  RequestCountPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ALBRequestCountPerTarget
          ResourceLabel: !Sub
            - ${ALBFullName}/${TGFullName}
            - ALBFullName: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName
              TGFullName: !GetAtt TargetGroup.TargetGroupFullName
        TargetValue: 1000
        DisableScaleIn: false

Outputs:
  LoadBalancerDNS:
    Description: ALB DNS name
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub ${EnvironmentName}-LoadBalancerDNS

  LoadBalancerArn:
    Description: ALB ARN
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub ${EnvironmentName}-LoadBalancerArn

  TargetGroupArn:
    Description: Target Group ARN
    Value: !Ref TargetGroup
    Export:
      Name: !Sub ${EnvironmentName}-TargetGroupArn

  AutoScalingGroupName:
    Description: Auto Scaling Group name
    Value: !Ref AutoScalingGroup
    Export:
      Name: !Sub ${EnvironmentName}-AutoScalingGroupName
