AWSTemplateFormatVersion: '2010-09-09'
Description: 'NetworkScanScada - Phase 3: AWS WAF and Security Configuration'

Parameters:
  EnvironmentName:
    Description: Environment name
    Type: String
    Default: production

  RateLimitPerIP:
    Description: Maximum requests per 5 minutes per IP
    Type: Number
    Default: 2000

  EnableSQLiProtection:
    Description: Enable SQL injection protection
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  EnableXSSProtection:
    Description: Enable XSS protection
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

Resources:
  # ==================== WAF Web ACL ====================
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub ${EnvironmentName}-networkscan-waf
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      Description: WAF Web ACL for NetworkScan application
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub ${EnvironmentName}NetworkScanWAF
      Rules:
        # AWS Managed Rules - Core Rule Set
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules:
                - Name: SizeRestrictions_BODY
                - Name: GenericRFI_BODY
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSet

        # AWS Managed Rules - Known Bad Inputs
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesKnownBadInputsRuleSet

        # AWS Managed Rules - SQL Injection
        - Name: AWSManagedRulesSQLiRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesSQLiRuleSet

        # AWS Managed Rules - Linux OS
        - Name: AWSManagedRulesLinuxRuleSet
          Priority: 4
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesLinuxRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesLinuxRuleSet

        # AWS Managed Rules - PHP Application
        - Name: AWSManagedRulesPHPRuleSet
          Priority: 5
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesPHPRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesPHPRuleSet

        # Rate Limiting Rule
        - Name: RateLimitRule
          Priority: 6
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              Limit: !Ref RateLimitPerIP
              AggregateKeyType: IP
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule

        # Block Bad Bots
        - Name: AWSManagedRulesBotControlRuleSet
          Priority: 7
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesBotControlRuleSet
              ManagedRuleGroupConfigs:
                - AWSManagedRulesBotControlRuleSet:
                    InspectionLevel: COMMON
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesBotControlRuleSet

        # Block requests from anonymous proxies
        - Name: AWSManagedRulesAnonymousIpList
          Priority: 8
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAnonymousIpList
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesAnonymousIpList

        # Custom Rule - Block suspicious user agents
        - Name: BlockSuspiciousUserAgents
          Priority: 9
          Action:
            Block: {}
          Statement:
            OrStatement:
              Statements:
                - ByteMatchStatement:
                    SearchString: sqlmap
                    FieldToMatch:
                      SingleHeader:
                        Name: user-agent
                    TextTransformations:
                      - Priority: 0
                        Type: LOWERCASE
                    PositionalConstraint: CONTAINS
                - ByteMatchStatement:
                    SearchString: nikto
                    FieldToMatch:
                      SingleHeader:
                        Name: user-agent
                    TextTransformations:
                      - Priority: 0
                        Type: LOWERCASE
                    PositionalConstraint: CONTAINS
                - ByteMatchStatement:
                    SearchString: nessus
                    FieldToMatch:
                      SingleHeader:
                        Name: user-agent
                    TextTransformations:
                      - Priority: 0
                        Type: LOWERCASE
                    PositionalConstraint: CONTAINS
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BlockSuspiciousUserAgents

        # Custom Rule - Geo Blocking (Optional - currently set to count only)
        - Name: GeoBlockRule
          Priority: 10
          Action:
            Count: {}
          Statement:
            GeoMatchStatement:
              CountryCodes:
                - KP  # North Korea
                - IR  # Iran
                - SY  # Syria
                - CU  # Cuba
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: GeoBlockRule

      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-networkscan-waf
        - Key: Environment
          Value: !Ref EnvironmentName

  # ==================== WAF Association with ALB ====================
  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !ImportValue
        Fn::Sub: ${EnvironmentName}-ALBArn
      WebACLArn: !GetAtt WebACL.Arn

  # ==================== WAF Logging ====================
  WAFLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub aws-waf-logs-${EnvironmentName}-networkscan
      RetentionInDays: 90
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-waf-logs
        - Key: Environment
          Value: !Ref EnvironmentName

  WAFLoggingConfiguration:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      ResourceArn: !GetAtt WebACL.Arn
      LogDestinationConfigs:
        - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:aws-waf-logs-${EnvironmentName}-networkscan
      LoggingFilter:
        DefaultBehavior: KEEP
        Filters:
          - Behavior: KEEP
            Conditions:
              - ActionCondition:
                  Action: BLOCK
            Requirement: MEETS_ANY
      RedactedFields:
        - SingleHeader:
            Name: authorization
        - SingleHeader:
            Name: cookie

  # ==================== CloudTrail ====================
  CloudTrailBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${EnvironmentName}-networkscan-cloudtrail-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 90
            ExpirationInDays: 365
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-cloudtrail-bucket
        - Key: Environment
          Value: !Ref EnvironmentName

  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub arn:aws:s3:::${CloudTrailBucket}
            Condition:
              StringEquals:
                aws:SourceArn: !Sub arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/${EnvironmentName}-networkscan-trail
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${CloudTrailBucket}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
                aws:SourceArn: !Sub arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/${EnvironmentName}-networkscan-trail

  CloudTrailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/cloudtrail/${EnvironmentName}-networkscan
      RetentionInDays: 90
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-cloudtrail-logs
        - Key: Environment
          Value: !Ref EnvironmentName

  CloudTrailRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-cloudtrail-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudTrailLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt CloudTrailLogGroup.Arn

  CloudTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: CloudTrailBucketPolicy
    Properties:
      TrailName: !Sub ${EnvironmentName}-networkscan-trail
      S3BucketName: !Ref CloudTrailBucket
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true
      CloudWatchLogsLogGroupArn: !GetAtt CloudTrailLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt CloudTrailRole.Arn
      EventSelectors:
        - ReadWriteType: All
          IncludeManagementEvents: true
          DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Sub arn:aws:s3:::${EnvironmentName}-networkscan-reports/
                - !Sub arn:aws:s3:::${EnvironmentName}-networkscan-uploads/
                - !Sub arn:aws:s3:::${EnvironmentName}-networkscan-backups/
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-cloudtrail
        - Key: Environment
          Value: !Ref EnvironmentName

  # ==================== Security Hub ====================
  SecurityHub:
    Type: AWS::SecurityHub::Hub
    Properties:
      Tags:
        Environment: !Ref EnvironmentName

  # ==================== GuardDuty ====================
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      FindingPublishingFrequency: FIFTEEN_MINUTES
      DataSources:
        S3Logs:
          Enable: true
        Kubernetes:
          AuditLogs:
            Enable: false
        MalwareProtection:
          ScanEc2InstanceWithFindings:
            EbsVolumes: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-guardduty
        - Key: Environment
          Value: !Ref EnvironmentName

  # ==================== Config Rules ====================
  ConfigRecorderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-config-recorder-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWS_ConfigRole

  # ==================== IP Sets for Custom Rules ====================
  AllowedIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: !Sub ${EnvironmentName}-allowed-ips
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses: []
      Description: Allowed IP addresses for admin access
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-allowed-ips
        - Key: Environment
          Value: !Ref EnvironmentName

  BlockedIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: !Sub ${EnvironmentName}-blocked-ips
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses: []
      Description: Blocked IP addresses
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-blocked-ips
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  WebACLArn:
    Description: WAF Web ACL ARN
    Value: !GetAtt WebACL.Arn
    Export:
      Name: !Sub ${EnvironmentName}-WebACLArn

  WebACLId:
    Description: WAF Web ACL ID
    Value: !Ref WebACL
    Export:
      Name: !Sub ${EnvironmentName}-WebACLId

  CloudTrailArn:
    Description: CloudTrail ARN
    Value: !GetAtt CloudTrail.Arn
    Export:
      Name: !Sub ${EnvironmentName}-CloudTrailArn

  GuardDutyDetectorId:
    Description: GuardDuty Detector ID
    Value: !Ref GuardDutyDetector
    Export:
      Name: !Sub ${EnvironmentName}-GuardDutyDetectorId

  AllowedIPSetArn:
    Description: Allowed IP Set ARN
    Value: !GetAtt AllowedIPSet.Arn
    Export:
      Name: !Sub ${EnvironmentName}-AllowedIPSetArn

  BlockedIPSetArn:
    Description: Blocked IP Set ARN
    Value: !GetAtt BlockedIPSet.Arn
    Export:
      Name: !Sub ${EnvironmentName}-BlockedIPSetArn
